package com.lms.classsystem.controller;

import com.lms.classsystem.dto.GradeRequestDTO;
import com.lms.classsystem.entity.Assignment;
import com.lms.classsystem.entity.Student;
import com.lms.classsystem.entity.Submission;
import com.lms.classsystem.repository.AssignmentRepository;
import com.lms.classsystem.repository.StudentRepository;
import com.lms.classsystem.repository.SubmissionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/submission")
@CrossOrigin
public class SubmissionController {

    @Autowired
    private SubmissionRepository submissionRepository;
    
    @Autowired
    private StudentRepository studentRepository;
    
    @Autowired
    private AssignmentRepository assignmentRepository;

    @Value("${app.upload.dir}")
    private String uploadDir;

    // ==========================================
    // 1. THE FILE UPLOAD METHOD (NOW WITH DB SAVE)
    // ==========================================
    @PostMapping("/submit")
    public ResponseEntity<?> submitAssignment(
            @RequestParam("assignmentId") Long assignmentId,
            @RequestParam("studentId") Long studentId,
            @RequestParam("file") MultipartFile file) {
        
        if (file.isEmpty()) {
            return ResponseEntity.badRequest().body("Transmission payload cannot be empty.");
        }

        try {
            File directory = new File(uploadDir);
            if (!directory.exists()) {
                directory.mkdirs();
            }

            String originalFileName = file.getOriginalFilename();
            String uniqueFileName = UUID.randomUUID().toString() + "_" + originalFileName;
            
            Path targetPath = Paths.get(uploadDir).resolve(uniqueFileName);
            Files.copy(file.getInputStream(), targetPath);

            String fileUrlPath = "/uploads/submissions/" + uniqueFileName;

            // --- THE FIX: ACTUALLY SAVE TO MYSQL ---
            Student student = studentRepository.findById(studentId)
                    .orElseThrow(() -> new RuntimeException("Student ID not found in registry"));
            
            Assignment assignment = assignmentRepository.findById(assignmentId)
                    .orElseThrow(() -> new RuntimeException("Assignment ID not found in registry"));

            Submission newSubmission = new Submission();
            newSubmission.setStudent(student);
            newSubmission.setAssignment(assignment);
            newSubmission.setFileUrl(fileUrlPath);
            // submittedAt is auto-generated by your entity class!

            submissionRepository.save(newSubmission);
            // ---------------------------------------

            return ResponseEntity.ok(Map.of(
                "status", "SUCCESS",
                "message", "Payload securely archived and recorded in database",
                "filePath", fileUrlPath
            ));

        } catch (Exception e) {
            return ResponseEntity.status(500).body("System fault: " + e.getMessage());
        }
    }

    // ==========================================
    // 2. THE GRADING & FEEDBACK METHOD
    // ==========================================
    @PutMapping("/grade/{submissionId}")
    public ResponseEntity<?> gradeSubmission(
            @PathVariable Long submissionId, 
            @RequestBody GradeRequestDTO gradeData) {
        
        try {
            Submission submission = submissionRepository.findById(submissionId)
                    .orElseThrow(() -> new RuntimeException("Submission record not found."));

            submission.setGrade(gradeData.getGrade());
            submission.setFeedback(gradeData.getFeedback());

            submissionRepository.save(submission);

            return ResponseEntity.ok(Map.of(
                "status", "SUCCESS",
                "message", "Evaluation successfully recorded."
            ));

        } catch (Exception e) {
            return ResponseEntity.status(500).body("Grading system error: " + e.getMessage());
        }
    }

    // ==========================================
    // 3. FETCH ALL SUBMISSIONS 
    // ==========================================
    @GetMapping("/get-all")
    public ResponseEntity<?> getAllSubmissions() {
        try {
            java.util.List<Submission> allSubmissions = submissionRepository.findAll();
            return ResponseEntity.ok(allSubmissions);
        } catch (Exception e) {
            return ResponseEntity.status(500).body("Failed to retrieve submissions: " + e.getMessage());
        }
    }
    
 // ==========================================
    // 4. FETCH SUBMISSIONS BY ASSIGNMENT ID
    // ==========================================
    @GetMapping("/assignment/{assignmentId}")
    public ResponseEntity<?> getSubmissionsByAssignment(@PathVariable Long assignmentId) {
        try {
            // Note: If you don't have this method in your repository yet, 
            // we will need to add it to SubmissionRepository.java!
            java.util.List<Submission> submissions = submissionRepository.findByAssignmentId(assignmentId);
            return ResponseEntity.ok(submissions);
        } catch (Exception e) {
            return ResponseEntity.status(500).body("Database query failed: " + e.getMessage());
        }
    }
}